[build]
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://dust.devbitapp.be/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false